(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY="strengthTrainingTrackerV2";
const levels={heavy:0,medium:1,light:2}, names={heavy:"Heavy",medium:"Medium",light:"Light"};
const E=(cat,name,h,m,l,compound=false,body=false)=>({cat,name,rx:[h,m,l],compound,body});
const templates={
UA:{name:"Upper A",focus:"Bench press + barbell row",ex:[E("Primary","Bench Press",[3,"4"],[3,"6"],[3,"8"],1),E("Primary","Barbell Row",[3,"6"],[3,"6"],[3,"8"],1),E("Secondary","Incline Dumbbell Press",[2,"8"],[2,"8"],[3,"10"]),E("Secondary","Dumbbell Row",[2,"8"],[2,"8"],[2,"10"]),E("Arms","Biceps Curl Variation",[3,"8"],[3,"10"],[3,"12"]),E("Arms","Triceps Extension Variation",[3,"8"],[3,"10"],[3,"12"]),E("Accessory","Rear Delt / Face Pull",[3,"8"],[3,"10"],[3,"12"]),E("Accessory","Lateral Raise Variation",[3,"8"],[3,"10"],[3,"12"]) ]},
UB:{name:"Upper B",focus:"OHP + weighted pull-up",ex:[E("Primary","Weighted Pull-up",[3,"5"],[2,"7"],[2,"10"],1,1),E("Primary","Barbell Overhead Press",[3,"5"],[2,"7"],[2,"10"],1),E("Secondary","Dumbbell Row",[2,"8"],[2,"8"],[2,"12"]),E("Secondary","Weighted Dip / Flat DB Press",[2,"8"],[2,"8"],[2,"12"],1),E("Arms","Biceps Curl Variation",[3,"8"],[3,"10"],[3,"12"]),E("Arms","Triceps Extension Variation",[3,"8"],[3,"10"],[3,"12"]),E("Accessory","Rear Delt / Face Pull",[3,"10"],[3,"10"],[3,"12"]),E("Accessory","Lateral Raise Variation",[3,"10"],[3,"10"],[3,"12"]) ]},
LA:{name:"Lower A",focus:"Back squat + Romanian deadlift",ex:[E("Primary","Back Squat",[3,"3"],[2,"5"],[2,"8"],1),E("Core","Hanging Leg Raise",[3,"8"],[2,"10"],[2,"8"]),E("Secondary","Romanian Deadlift",[2,"6"],[2,"7"],[2,"10"],1),E("Posterior","Reverse Hyperextension",[3,"12"],[2,"12"],[2,"12"]),E("Accessory","Leg Curl",[2,"10"],[2,"12"],[2,"10"]),E("Accessory","Leg Extension",[2,"10"],[2,"12"],[2,"10"]),E("Lower leg","Calf Raise",[3,"12"],[3,"12"],[3,"12"]),E("Lower leg","Tibialis Raise",[3,"12"],[3,"12"],[3,"12"]),E("Core","Ab Variation",[3,"12"],[3,"12"],[3,"12"]) ]},
LB:{name:"Lower B",focus:"Deadlift + front squat",ex:[E("Primary","Deadlift",[3,"1 / 3 / 5"],[3,"3 / 5 / 7"],[3,"6"],1),E("Mobility","Spinal Decompression",[1,"—"],[1,"—"],[1,"—"]),E("Secondary","Front Squat",[3,"5"],[3,"8"],[3,"10"],1),E("Core","Hanging Leg Raise",[3,"12"],[3,"12"],[3,"10"]),E("Accessory","Leg Curl",[2,"10"],[2,"12"],[2,"10"]),E("Accessory","Leg Extension",[2,"10"],[2,"12"],[2,"10"]),E("Lower leg","Calf Raise",[3,"12"],[3,"12"],[3,"12"]),E("Lower leg","Tibialis Raise",[3,"12"],[3,"12"],[3,"12"]),E("Core","Ab Variation",[3,"12"],[3,"12"],[3,"12"]) ]}};
const sequence=[["UA","heavy"],["LA","medium"],["UB","light"],["LB","heavy"],["UA","medium"],["LA","light"],["UB","heavy"],["LB","medium"],["UA","light"],["LA","heavy"],["UB","medium"],["LB","light"]];
const conditioning=["None","Assault bike · 3 × 1 min","Rower · 3 × 1 min","Zone 2 · 20–30 min"];
const sessions=sequence.map((x,i)=>{let t=templates[x[0]],lv=levels[x[1]];return{id:i+1,key:x[0],intensity:x[1],name:`${names[x[1]]} ${t.name}`,focus:t.focus,ex:t.ex.map(e=>({...e,sets:e.rx[lv][0],reps:e.rx[lv][1]}))}});
const fresh=()=>({current:1,done:[],drafts:{},notes:{},conditioning:{},history:[],bw:88,theme:"system"});let state=fresh();try{state={...state,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
const saveState=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast("Storage unavailable — export a backup")}};
const session=()=>sessions[state.current-1], draftKey=i=>`${state.current}-${i}`;
function draft(i,e){let k=draftKey(i);if(!state.drafts[k])state.drafts[k]=Array.from({length:e.sets},()=>({kg:"",reps:"",rpe:"",done:false}));return state.drafts[k]}
function e1rm(set,e){let kg=+set.kg,reps=+set.reps;if(!(kg>=0&&reps>0))return null;if(e.body){let total=kg+(+state.bw||0);return total*(1+reps/30)-(+state.bw||0)}return kg*(1+reps/30)}
function esc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function toast(msg){let el=$("#toast");el.textContent=msg;el.classList.add("on");clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove("on"),2200)}
function go(n){state.current=(n+11)%12+1;saveState();renderAll();window.scrollTo({top:0,behavior:"smooth"})}
function renderRail(){$("#rail").innerHTML=sessions.map(s=>`<button class="sessionDot ${s.intensity} ${s.id===state.current?"current":""} ${state.done.includes(s.id)?"done":""}" data-session="${s.id}" aria-label="Session ${s.id}: ${s.name}">${state.done.includes(s.id)?"✓":s.id}</button>`).join("")}
function lastFor(name){for(let i=state.history.length-1;i>=0;i--){let x=state.history[i].sets.filter(s=>s.exercise===name).sort((a,b)=>b.e1-a.e1)[0];if(x)return x}return null}
function setHTML(set,j,e,i){let est=e1rm(set,e);return `<div class="set" data-i="${i}" data-j="${j}"><span class="setNo">${j+1}</span><input class="field" data-k="kg" type="number" step="0.5" inputmode="decimal" value="${esc(set.kg)}" placeholder="kg" aria-label="Weight set ${j+1}"><input class="field" data-k="reps" type="number" inputmode="numeric" value="${esc(set.reps)}" placeholder="reps" aria-label="Reps set ${j+1}"><input class="field rpe" data-k="rpe" type="number" step="0.5" inputmode="decimal" value="${esc(set.rpe)}" placeholder="RPE" aria-label="RPE set ${j+1}"><span class="e1">${est?Math.round(est)+" e1":""}</span><button class="tick ${set.done?"done":""}" data-act="tick" aria-label="Complete set">${set.done?"✓":""}</button><button class="delete" data-act="delete" aria-label="Delete set">×</button></div>`}
function renderWorkout(){let s=session();$("#position").textContent=`Session ${String(s.id).padStart(2,"0")} of 12`;$("#title").textContent=s.name;$("#focus").textContent=s.focus;$("#level").className=`badge ${s.intensity}`;$("#level").textContent=names[s.intensity];$("#notes").value=state.notes[s.id]||"";$("#cue").textContent=s.intensity==="heavy"?"Take full rests and leave a clean rep in reserve.":s.intensity==="medium"?"Build crisp volume without grinding.":"Move well, own every rep and recover for the next exposure.";$("#exercises").innerHTML=s.ex.map((e,i)=>{let last=lastFor(e.name);return `<article class="card exercise"><div class="exerciseHead"><div><span class="tag">${e.cat}</span><h3>${e.name}</h3><small class="muted">${last?`Last: ${last.kg} kg × ${last.reps}`:"No history yet"}</small></div><span class="rx">${e.sets} × ${e.reps}</span><button class="add" data-act="add" data-i="${i}" aria-label="Add set">+</button></div><div class="sets">${draft(i,e).map((x,j)=>setHTML(x,j,e,i)).join("")}</div></article>`}).join("");$("#conditioning").innerHTML=conditioning.map((c,i)=>`<button class="choice ${state.conditioning[s.id]===i?"on":""}" data-cond="${i}">${c}</button>`).join("");progress()}
function progress(){let total=0,done=0;session().ex.forEach((e,i)=>draft(i,e).forEach(x=>{total++;if(x.done)done++}));let p=total?done/total:0;$("#summary").textContent=`${done} of ${total} sets complete`;$("#percent").textContent=`${Math.round(p*100)}%`;$("#ring").style.strokeDashoffset=113.1*(1-p)}
function renderPlan(){$("#planGrid").innerHTML=sessions.map(s=>`<button class="card planCard ${s.id===state.current?"current":""}" data-session="${s.id}"><span class="badge ${s.intensity}">${names[s.intensity]}</span><h3>${String(s.id).padStart(2,"0")} · ${templates[s.key].name}</h3><p class="muted">${s.focus} · ${s.ex.length} exercises ${state.done.includes(s.id)?"· Completed":""}</p></button>`).join("")}
function saveWorkout(){let s=session(),sets=[];s.ex.forEach((e,i)=>draft(i,e).forEach(x=>{let est=e1rm(x,e);if(+x.reps>0&&+x.kg>=0)sets.push({exercise:e.name,kg:+x.kg,reps:+x.reps,rpe:x.rpe?+x.rpe:null,e1:est||+x.kg,compound:e.compound})}));if(!sets.length&&!confirm("Save this workout without logged sets?"))return;state.history.push({id:Date.now(),date:new Date().toISOString(),session:s.id,name:s.name,notes:state.notes[s.id]||"",conditioning:conditioning[state.conditioning[s.id]??0],sets});if(!state.done.includes(s.id))state.done.push(s.id);s.ex.forEach((_,i)=>delete state.drafts[draftKey(i)]);let old=s.name;state.current=s.id%12+1;saveState();renderAll();toast(`${old} saved`)}
function points(lift){return state.history.map(h=>{let matches=h.sets.filter(x=>x.exercise===lift&&x.compound);if(!matches.length)return null;let best=matches.sort((a,b)=>b.e1-a.e1)[0];return{...best,date:h.date}}).filter(Boolean)}
function renderProgress(){$("#bw").value=state.bw;let lifts=[...new Set(state.history.flatMap(h=>h.sets.filter(x=>x.compound).map(x=>x.exercise)))],prior=$("#lift").value;$("#lift").innerHTML=lifts.length?lifts.map(x=>`<option>${esc(x)}</option>`).join(""):`<option>No compound data</option>`;if(lifts.includes(prior))$("#lift").value=prior;let pts=lifts.length?points($("#lift").value):[],all=state.history.flatMap(h=>h.sets),best=pts.length?Math.max(...pts.map(x=>x.e1)):null;$("#stats").innerHTML=[["Workouts",state.history.length],["Sets logged",all.length],["Cycle",`${state.done.length}/12`],["Selected best",best?`${Math.round(best)} kg`:"—"]].map(x=>`<article class="card stat"><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join("");draw(pts);$("#history").innerHTML=state.history.length?state.history.slice(-10).reverse().map(h=>`<div class="historyRow"><span>${new Date(h.date).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"2-digit"})}</span><strong>${h.name}</strong><b>${h.sets.length} sets</b></div>`).join(""):`<div class="empty">Save your first workout to build training history.</div>`}
function draw(pts){let el=$("#chart");if(!pts.length){el.innerHTML=`<div class="empty">Log a compound lift and save the workout to see a trend.</div>`;return}let vals=pts.map(x=>x.e1),lo=Math.min(...vals)-3,hi=Math.max(...vals)+3,span=hi-lo||1,xy=vals.map((v,i)=>[35+(pts.length===1?250:i/(pts.length-1)*520),210-(v-lo)/span*165]),path=xy.map((p,i)=>(i?"L":"M")+p.join(" " )).join(" ");el.innerHTML=`<svg viewBox="0 0 590 240" preserveAspectRatio="none" role="img" aria-label="Estimated one rep max trend"><defs><linearGradient id="stroke"><stop stop-color="#2367f2"/><stop offset="1" stop-color="#7546e8"/></linearGradient></defs><path d="M35 45H555M35 127H555M35 210H555" stroke="currentColor" opacity=".1"/><path d="${path}" fill="none" stroke="url(#stroke)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/>${xy.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="var(--solid)" stroke="#2367f2" stroke-width="3"><title>${Math.round(vals[i])} kg</title></circle>`).join("")}<text x="35" y="25" fill="currentColor" opacity=".55">${Math.round(hi)} kg</text><text x="35" y="233" fill="currentColor" opacity=".55">${Math.round(lo)} kg</text></svg>`}
function exportData(){let a=document.createElement("a"),blob=new Blob([JSON.stringify({...state,app:"Strength Training Tracker",version:2},null,2)],{type:"application/json"});a.href=URL.createObjectURL(blob);a.download="strength-training-tracker-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function applyTheme(){let dark=state.theme==="dark"||(state.theme==="system"&&matchMedia("(prefers-color-scheme:dark)").matches);document.body.dataset.theme=dark?"dark":"light";$("#theme").title=`Theme: ${state.theme}`}
function renderAll(){renderRail();renderWorkout();renderPlan();renderProgress();applyTheme()}
document.addEventListener("click",e=>{let v=e.target.closest("[data-view]");if(v){let id=v.dataset.view;$$('.view').forEach(x=>x.classList.toggle("on",x.id===id));$$('[data-view]').forEach(x=>x.classList.toggle("on",x.dataset.view===id));if(id==="progress")renderProgress();return}let ss=e.target.closest("[data-session]");if(ss){go(+ss.dataset.session);$$('.view').forEach(x=>x.classList.toggle("on",x.id==="train"));return}let c=e.target.closest("[data-cond]");if(c){state.conditioning[state.current]=+c.dataset.cond;saveState();renderWorkout();return}let a=e.target.closest("[data-act]");if(a){let row=a.closest(".set"),i=+(row?.dataset.i??a.dataset.i),j=+row?.dataset.j,d=draft(i,session().ex[i]);if(a.dataset.act==="add")d.push({kg:"",reps:"",rpe:"",done:false});if(a.dataset.act==="tick")d[j].done=!d[j].done;if(a.dataset.act==="delete")d.splice(j,1);saveState();renderWorkout()}});
$("#exercises").addEventListener("input",e=>{if(!e.target.dataset.k)return;let row=e.target.closest(".set"),x=draft(+row.dataset.i,session().ex[+row.dataset.i])[+row.dataset.j];x[e.target.dataset.k]=e.target.value;saveState();let out=row.querySelector(".e1"),n=e1rm(x,session().ex[+row.dataset.i]);out.textContent=n?Math.round(n)+" e1":""});
$("#notes").addEventListener("input",e=>{state.notes[state.current]=e.target.value;saveState()});$("#prev").onclick=()=>go(state.current-1);$("#next").onclick=()=>go(state.current+1);$("#save").onclick=saveWorkout;$("#lift").onchange=renderProgress;$("#bw").onchange=e=>{state.bw=Math.max(0,+e.target.value||0);saveState();renderProgress()};$$('.export').forEach(x=>x.onclick=exportData);$("#import").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.history))throw 0;state={...fresh(),...x};saveState();renderAll();toast("Backup restored")}catch{toast("That backup could not be read")}};r.readAsText(f);e.target.value=""};$("#reset").onclick=()=>{if(confirm("Reset cycle progress and drafts? Saved history will be kept.")){state.current=1;state.done=[];state.drafts={};state.notes={};state.conditioning={};saveState();renderAll();toast("Cycle reset")}};$("#theme").onclick=()=>{state.theme=state.theme==="system"?"light":state.theme==="light"?"dark":"system";saveState();applyTheme();toast(`Theme: ${state.theme}`)};matchMedia("(prefers-color-scheme:dark)").addEventListener?.("change",applyTheme);if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));renderAll();
})();