/* Historical V4 extension. Not loaded by the V5 application; retained for reference only.
(()=>{"use strict";const BASE='strengthTrainingTrackerV2',OLD='cycleLogV1',PRO='strengthTrainingTrackerProV1',q=s=>document.querySelector(s);
function read(k,f={}){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function migrate(){let current=read(BASE,null),old=read(OLD,null);if(current&&Array.isArray(current.history)&&current.history.length)return;if(!old||!Array.isArray(old.history))return;write(BASE,{current:+old.cur||1,done:Array.isArray(old.done)?old.done:[],drafts:old.draft||{},notes:old.notes||{},conditioning:old.choice||{},history:old.history,bw:+old.bw||88,theme:'system'});if(!sessionStorage.getItem('stt-migrated')){sessionStorage.setItem('stt-migrated','1');location.reload()}}migrate();
let pro=read(PRO,{readiness:{},started:null,session:null});let timer=null,remaining=0,endAt=0;
function base(){return read(BASE,{history:[],current:1,done:[]})}function persist(){write(PRO,pro)}function fmt(sec){sec=Math.max(0,sec|0);return `${String(sec/60|0).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}function nice(n){return Intl.NumberFormat('en-GB',{notation:n>9999?'compact':'standard',maximumFractionDigits:1}).format(n)}
function inject(){let meta=q('.hero .meta');if(meta&&!q('#sessionTime'))meta.insertAdjacentHTML('beforeend','<span class="pro-session-time" id="sessionTime">00:00</span>');let aside=q('#train aside'),cue=aside?.lastElementChild;if(aside&&!q('#readinessPanel'))cue.insertAdjacentHTML('beforebegin','<article class="card panel" id="readinessPanel"><h2>Readiness</h2><div class="readiness"><label class="readiness-row"><span>Energy</span><input data-ready="energy" type="range" min="1" max="5" value="3"><output>3</output></label><label class="readiness-row"><span>Sleep</span><input data-ready="sleep" type="range" min="1" max="5" value="3"><output>3</output></label><label class="readiness-row"><span>Joints</span><input data-ready="joints" type="range" min="1" max="5" value="3"><output>3</output></label></div></article>');if(!q('#restDock'))document.body.insertAdjacentHTML('beforeend','<section class="rest-dock min" id="restDock" aria-label="Rest timer"><div class="rest-top"><div><div class="rest-label">Rest timer</div><div class="rest-time" id="restTime">00:00</div></div><button class="rest-toggle" id="restToggle" aria-label="Expand rest timer">＋</button></div><div class="rest-presets" hidden><button data-rest="60">1:00</button><button data-rest="90">1:30</button><button data-rest="120">2:00</button><button data-rest="180">3:00</button></div></section>');let stats=q('#stats');if(stats&&!q('#proAnalytics'))stats.insertAdjacentHTML('afterend','<div class="pro-grid" id="proAnalytics"><article class="card pro-panel"><h2>Four-week workload</h2><p class="muted">Logged tonnage by week</p><div class="volume-bars" id="volumeBars"></div></article><article class="card pro-panel"><h2>Performance pulse</h2><div id="pulse"></div></article></div><article class="card pro-panel" id="achievementsPanel"><h2>Recent highlights</h2><div id="achievements"></div><div class="data-note">Your records stay on this device. Export a backup periodically, especially before clearing browser data.</div></article>');bind();sync();analytics()}
function bind(){document.addEventListener('input',e=>{if(e.target.matches('#exercises input'))startSession();if(e.target.dataset.ready){let b=base(),key=String(b.current),r=pro.readiness[key]||{};r[e.target.dataset.ready]=+e.target.value;r.date=new Date().toISOString();pro.readiness[key]=r;e.target.nextElementSibling.value=e.target.value;persist()}});document.addEventListener('click',e=>{if(e.target.closest('.tick')){startSession();startRest(90)}if(e.target.closest('#save'))setTimeout(()=>{pro.started=null;pro.session=null;persist();sync();analytics()},80);let r=e.target.closest('[data-rest]');if(r)startRest(+r.dataset.rest)});q('#restToggle').onclick=()=>{let d=q('#restDock'),open=d.classList.toggle('min');q('.rest-presets').hidden=open;q('#restToggle').textContent=open?'＋':'−'};setInterval(()=>{syncClock();if(q('#progress.view.on'))analytics()},1000)}
function startSession(){let b=base();if(pro.started&&pro.session===b.current)return;pro.started=Date.now();pro.session=b.current;persist();syncClock()}function syncClock(){let el=q('#sessionTime');if(el){let b=base(),seconds=pro.started&&pro.session===b.current?(Date.now()-pro.started)/1000:0;el.textContent=fmt(seconds)}if(endAt){remaining=Math.ceil((endAt-Date.now())/1000);q('#restTime').textContent=fmt(remaining);if(remaining<=0){clearInterval(timer);timer=null;endAt=0;q('#restDock').classList.remove('running');q('#restDock').classList.add('done');q('#restTime').textContent='DONE';navigator.vibrate?.([120,80,120]);setTimeout(()=>q('#restDock').classList.remove('done'),2500)}}}
function startRest(sec){clearInterval(timer);remaining=sec;endAt=Date.now()+sec*1000;q('#restDock').classList.remove('min','done');q('.rest-presets').hidden=false;q('#restToggle').textContent='−';q('#restDock').classList.add('running');syncClock();timer=setInterval(syncClock,250)}
function sync(){let b=base(),r=pro.readiness[String(b.current)]||{};document.querySelectorAll('[data-ready]').forEach(x=>{x.value=r[x.dataset.ready]||3;x.nextElementSibling.value=x.value});syncClock()}function weekStart(d){let x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}function volume(h){return (h.sets||[]).reduce((a,s)=>a+(+s.kg||0)*(+s.reps||0),0)}
function analytics(){let b=base(),hist=Array.isArray(b.history)?b.history:[],now=new Date(),weeks=Array.from({length:4},(_,i)=>{let start=weekStart(now);start.setDate(start.getDate()-(3-i)*7);return{start,end:new Date(+start+7*864e5),v:0,label:start.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}});hist.forEach(h=>{let d=new Date(h.date),w=weeks.find(x=>d>=x.start&&d<x.end);if(w)w.v+=volume(h)});let max=Math.max(1,...weeks.map(w=>w.v));let bars=q('#volumeBars');if(bars)bars.innerHTML=weeks.map(w=>`<div class="volume-col"><div class="volume-bar" style="height:${Math.max(3,w.v/max*100)}%" title="${Math.round(w.v)} kg"></div><small>${w.label}</small></div>`).join('');let recent=hist.filter(h=>Date.now()-new Date(h.date)<28*864e5),sets=recent.flatMap(h=>h.sets||[]),tonnage=sets.reduce((a,s)=>a+(+s.kg||0)*(+s.reps||0),0),rpes=sets.map(s=>+s.rpe).filter(Boolean),avg=rpes.length?rpes.reduce((a,n)=>a+n,0)/rpes.length:0,days=new Set(recent.map(h=>new Date(h.date).toDateString())).size;let pulse=q('#pulse');if(pulse)pulse.innerHTML=[['Training days · 28d',days],['Working sets · 28d',sets.length],['Tonnage · 28d',nice(tonnage)+' kg'],['Average RPE',avg?avg.toFixed(1):'—']].map(x=>`<div class="metric-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');highlights(hist)}
function highlights(hist){let records={},high=[];hist.forEach(h=>(h.sets||[]).filter(s=>s.compound&&isFinite(s.e1)).forEach(s=>{if(!records[s.exercise]||s.e1>records[s.exercise].e1)records[s.exercise]={...s,date:h.date}}));Object.entries(records).sort((a,b)=>new Date(b[1].date)-new Date(a[1].date)).slice(0,5).forEach(([name,r])=>high.push(`<div class="achievement"><span class="achievement-icon">PR</span><div><b>${name} · ${Math.round(r.e1)} kg e1RM</b><small>${r.kg} kg × ${r.reps} · ${new Date(r.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</small></div></div>`));let el=q('#achievements');if(el)el.innerHTML=high.length?high.join(''):'<p class="muted">Your strongest compound sets will appear here as you train.</p>'}inject();
})();
*/
